spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: api-gateway
  config:
    import: "optional:configserver:"
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-service
      username: ${CONFIG_NAME}
      password: ${CONFIG_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS}
    lease-renewal-interval-in-seconds: ${EUREKA_LEASE_RENEWAL_INTERVAL}
    lease-expiration-duration-in-seconds: ${EUREKA_LEASE_EXPIRATION_DURATION}
    hostname: ${EUREKA_HOSTNAME}
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
